version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - laravel
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: postgres:16-alpine
        container_name: postgres_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
